name: todolist_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  path: ^1.8.3
  path_provider: ^2.0.12
  animations: ^2.0.0 # Untuk animasi transisi
  firebase_core: ^3.9.0
  cloud_firestore: ^5.6.0
  flutter_svg: ^2.0.5  # For SVG support
  google_fonts: ^4.0.4  # For custom fonts
  provider: ^6.0.5  # For state management
  intl: ^0.18.1  # For date formatting
  shared_preferences: ^2.1.1  # For local storage
  flutter_local_notifications: ^18.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/flutter_logo.svg
    - assets/firebase_logo.svg